[servers]
    [servers.goods-service]
    timeout = "600000ms"
    addr = "39.108.84.221:28001"
    maxReceiveMessageSize = 0
    [servers.topic-service]
    timeout = "600000ms"
    addr = "39.108.84.221:28002"
    maxReceiveMessageSize = 0